/** §12 — UI metinleri sozlukte. */
export const tr = {
  app: { name: 'CariNet' },
  login: {
    title: 'Giris Yap',
    subtitle: 'Cari hesabinizi goruntuleyin',
    email: 'E-posta',
    password: 'Sifre',
    remember: 'Beni hatirla',
    submit: 'Giris yap',
    submitting: 'Giris yapiliyor...',
    error: 'Giris yapilamadi.',
  },
  home: {
    greeting: 'Merhaba',
    activeAccount: 'Aktif hesap',
    switchAccount: 'Hesap degistir',
    logout: 'Cikis yap',
    accountCode: 'Cari kodu',
    balance: 'Guncel bakiye',
    debt: 'Borc',
    credit: 'Alacak',
    creditLimit: 'Kredi limiti',
    limitUsage: 'Limit kullanimi',
    representative: 'Temsilci',
    recent: 'Son hareketler',
    statement: 'Ekstre',
    empty: 'Kayit yok.',
    balanceHint: 'Pozitif bakiye borclu oldugunuzu gosterir.',
  },
  statement: {
    title: 'Ekstre',
    runningBalance: 'Yuruyen bakiye',
    all: 'Tumu',
    last30: 'Son 30 gun',
    last90: 'Son 90 gun',
    loadingMore: 'Yukleniyor...',
    end: 'Tum hareketler yuklendi.',
  },
  invoice: {
    title: 'Fatura detayi',
    invoiceNo: 'Fatura no',
    date: 'Tarih',
    dueDate: 'Vade',
    items: 'Kalemler',
    quantity: 'Miktar',
    unitPrice: 'Birim fiyat',
    taxRate: 'KDV',
    lineTotal: 'Satir toplami',
    netTotal: 'Net toplam',
    taxTotal: 'KDV toplami',
    grandTotal: 'Genel toplam',
    exchangeRate: 'Kur',
    cancelled: 'IPTAL',
  },
  switcher: {
    title: 'Hesaplarim',
    hint: 'Goruntulemek istediginiz cari hesabi secin.',
  },
  common: { loading: 'Yukleniyor...', error: 'Bir hata olustu.', back: 'Geri' },
} as const;
