/** §12 — UI metinleri sozlukte. */
export const tr = {
  app: { name: 'CariNet' },
  login: {
    title: 'Giris Yap',
    subtitle: 'Cari hesabinizi goruntuleyin',
    email: 'E-posta',
    password: 'Sifre',
    remember: 'Beni hatirla',
    submit: 'Giris yap',
    submitting: 'Giris yapiliyor...',
    error: 'Giris yapilamadi.',
  },
  home: {
    greeting: 'Merhaba',
    activeAccount: 'Aktif hesap',
    switchAccount: 'Hesap degistir',
    logout: 'Cikis yap',
    accountCode: 'Cari kodu',
    balance: 'Guncel bakiye',
    debt: 'Borc',
    credit: 'Alacak',
    creditLimit: 'Kredi limiti',
    limitUsage: 'Limit kullanimi',
    representative: 'Temsilci',
    recent: 'Son hareketler',
    statement: 'Ekstre',
    overdue: 'Vadesi gecen',
    averageDue: 'Ortalama vade',
    empty: 'Kayit yok.',
    balanceHint: 'Pozitif bakiye borclu oldugunuzu gosterir.',
  },
  statement: {
    title: 'Ekstre',
    runningBalance: 'Yuruyen bakiye',
    sharePdf: 'PDF paylas',
    preparing: 'Hazirlaniyor...',
    all: 'Tumu',
    last30: 'Son 30 gun',
    last90: 'Son 90 gun',
    loadingMore: 'Yukleniyor...',
    end: 'Tum hareketler yuklendi.',
  },
  invoice: {
    title: 'Fatura detayi',
    invoiceNo: 'Fatura no',
    date: 'Tarih',
    dueDate: 'Vade',
    items: 'Kalemler',
    quantity: 'Miktar',
    unitPrice: 'Birim fiyat',
    taxRate: 'KDV',
    lineTotal: 'Satir toplami',
    netTotal: 'Net toplam',
    taxTotal: 'KDV toplami',
    grandTotal: 'Genel toplam',
    exchangeRate: 'Kur',
    cancelled: 'IPTAL',
  },
  switcher: {
    title: 'Hesaplarim',
    hint: 'Goruntulemek istediginiz cari hesabi secin.',
  },
  pay: {
    title: 'Odeme yap',
    cta: 'Odeme yap',
    amount: 'Odemek istediginiz tutar',
    payAll: 'Tum bakiyeyi ode',
    channel: 'Odeme yontemi',
    bankTransfer: 'Havale / EFT',
    card: 'Kredi karti',
    installment: 'Taksit',
    single: 'Tek cekim',
    submit: 'Odeme talebi olustur',
    creating: 'Olusturuluyor...',
    referenceTitle: 'Aciklamaya bu kodu yazin',
    referenceHint:
      'Kodu havale aciklamasina yazmazsaniz odemeniz otomatik eslesmez. Talep 72 saat gecerlidir.',
    copy: 'Kopyala',
    copied: 'Kopyalandi',
    share: 'Paylas',
    iban: 'IBAN',
    holder: 'Hesap sahibi',
    goToProvider: 'Guvenli odeme sayfasina git',
    providerHint:
      'Kart bilgileriniz bankanin/odeme kurulusunun sayfasinda alinir; bu uygulamada saklanmaz.',
    chargeNote: 'Karta cekilecek',
    debtNote: 'Borcunuzdan dusecek',
    surchargeHint: 'Aradaki fark taksit vade farkidir ve bankaya aittir.',
    pending: 'Bekleyen odeme talebiniz',
    done: 'Odemeniz alindiginda bakiyeniz otomatik guncellenir.',
    newRequest: 'Yeni talep olustur',
  },
  common: { loading: 'Yukleniyor...', error: 'Bir hata olustu.', back: 'Geri' },
} as const;
