/** §12 — UI metinleri sozlukte. */
export const tr = {
  app: { name: 'CariNet', tagline: 'B2B cari hesap platformu' },
  login: {
    title: 'Giris Yap',
    subtitle: 'Cari hesabinizi goruntuleyin',
    email: 'E-posta',
    password: 'Sifre',
    remember: 'Beni hatirla',
    submit: 'Giris yap',
    submitting: 'Giris yapiliyor...',
    error: 'Giris yapilamadi.',
    // Marka alani metni. Panelinki SATICIYA seslenir ("Alicilariniz..."); mobil uygulamayi
    // ALICI kullanir, o yuzden ayni cumle buraya kopyalanmaz.
    pitch: 'Bakiyeniz ve ekstreniz cebinizde.',
    pitchSub: 'Borcunuzu aninda gorun, faturayi inceleyin, odemenizi uygulamadan yapin.',
    privacy: 'Gizlilik ve KVKK',
  },
  home: {
    greeting: 'Merhaba',
    activeAccount: 'Aktif hesap',
    switchAccount: 'Hesap degistir',
    logout: 'Cikis yap',
    accountCode: 'Cari kodu',
    balance: 'Guncel bakiye',
    debt: 'Borc',
    credit: 'Alacak',
    creditLimit: 'Kredi limiti',
    limitUsage: 'Limit kullanimi',
    representative: 'Temsilci',
    recent: 'Son hareketler',
    statement: 'Ekstre',
    overdue: 'Vadesi gecen',
    averageDue: 'Ortalama vade',
    empty: 'Kayit yok.',
    balanceHint: 'Pozitif bakiye borclu oldugunuzu gosterir.',
  },
  statement: {
    title: 'Ekstre',
    runningBalance: 'Yuruyen bakiye',
    sharePdf: 'PDF paylas',
    preparing: 'Hazirlaniyor...',
    all: 'Tumu',
    last30: 'Son 30 gun',
    last90: 'Son 90 gun',
    loadingMore: 'Yukleniyor...',
    end: 'Tum hareketler yuklendi.',
  },
  invoice: {
    title: 'Fatura detayi',
    invoiceNo: 'Fatura no',
    date: 'Tarih',
    dueDate: 'Vade',
    items: 'Kalemler',
    quantity: 'Miktar',
    unitPrice: 'Birim fiyat',
    taxRate: 'KDV',
    lineTotal: 'Satir toplami',
    netTotal: 'Net toplam',
    taxTotal: 'KDV toplami',
    grandTotal: 'Genel toplam',
    exchangeRate: 'Kur',
    cancelled: 'IPTAL',
  },
  switcher: {
    title: 'Hesaplarim',
    hint: 'Goruntulemek istediginiz cari hesabi secin.',
    active: 'Aktif',
  },
  pay: {
    title: 'Odeme yap',
    cta: 'Odeme yap',
    amount: 'Odemek istediginiz tutar',
    payAll: 'Tum bakiyeyi ode',
    channel: 'Odeme yontemi',
    bankTransfer: 'Havale / EFT',
    card: 'Kredi karti',
    installment: 'Taksit',
    single: 'Tek cekim',
    submit: 'Odeme talebi olustur',
    creating: 'Olusturuluyor...',
    referenceTitle: 'Aciklamaya bu kodu yazin',
    referenceHint:
      'Kodu havale aciklamasina yazmazsaniz odemeniz otomatik eslesmez. Talep 72 saat gecerlidir.',
    copy: 'Kopyala',
    copied: 'Kopyalandi',
    share: 'Paylas',
    iban: 'IBAN',
    holder: 'Hesap sahibi',
    goToProvider: 'Guvenli odeme sayfasina git',
    providerHint:
      'Kart bilgileriniz bankanin/odeme kurulusunun sayfasinda alinir; bu uygulamada saklanmaz.',
    chargeNote: 'Karta cekilecek',
    debtNote: 'Borcunuzdan dusecek',
    surchargeHint: 'Aradaki fark taksit vade farkidir ve bankaya aittir.',
    pending: 'Bekleyen odeme talebiniz',
    done: 'Odemeniz alindiginda bakiyeniz otomatik guncellenir.',
    newRequest: 'Yeni talep olustur',
  },
  notifications: {
    title: 'Bildirimler',
    empty: 'Bildiriminiz yok.',
    markAll: 'Tumunu okundu isaretle',
    types: {
      NEW_INVOICE: 'Yeni fatura',
      DUE_REMINDER: 'Vade hatirlatma',
      COLLECTION_CONFIRMED: 'Tahsilat',
      CAMPAIGN: 'Kampanya',
      SYSTEM: 'Bilgilendirme',
    },
  },
  catalog: {
    title: 'Urunler',
    empty: 'Vitrinde urun yok.',
    inStock: 'Stokta',
    outOfStock: 'Stokta yok',
    search: 'Urun ara',
  },
  campaigns: {
    title: 'Kampanyalar',
    empty: 'Yayinda kampanya yok.',
    until: 'Son gun',
  },
  rates: {
    title: 'Doviz kurlari',
    hint: 'TCMB resmi satis kuru. Faturaniza yazilan kur, faturanin KESILDIGI gunun kurudur.',
    empty: 'Kur bilgisi yok.',
  },
  requests: {
    title: 'Talep ve oneri',
    new: 'Yeni talep',
    subject: 'Konu',
    body: 'Mesajiniz',
    type: 'Tur',
    types: {
      SUGGESTION: 'Oneri',
      COMPLAINT: 'Sikayet',
      RECONCILIATION_OBJECTION: 'Mutabakat itirazi',
      OTHER: 'Diger',
    },
    statuses: {
      OPEN: 'Acik',
      IN_PROGRESS: 'Isleniyor',
      RESOLVED: 'Cozuldu',
      CLOSED: 'Kapali',
    },
    send: 'Gonder',
    sending: 'Gonderiliyor...',
    reply: 'Satici yaniti',
    empty: 'Henuz talep acmadiniz.',
  },
  legal: {
    title: 'Gizlilik ve KVKK',
    link: 'Gizlilik ve KVKK',
    deleteLink: 'Hesabimi sil',
  },
  deleteAccount: {
    title: 'Hesabimi sil',
    intro:
      'Hesabinizi silerseniz kimlik bilgileriniz (ad, e-posta, telefon) anonimlestirilir ve tum oturumlariniz kapatilir. Bu islem GERI ALINAMAZ.',
    financialNote:
      'Yasal saklama geregi fatura ve hareket kayitlari satici firmanin defterinde kalir; ancak bu kayitlar artik sizin kimliginizle iliskilendirilmez.',
    passwordLabel: 'Sifreniz',
    confirmLabel: 'Onaylamak icin "HESABIMI SIL" yazin',
    confirmPhrase: 'HESABIMI SIL',
    submit: 'Hesabimi kalici olarak sil',
    cancel: 'Vazgec',
  },
  common: { loading: 'Yukleniyor...', error: 'Bir hata olustu.', back: 'Geri' },
  /** Alt sekmeler + baslik. Sekmede yalnizca gunluk 4 is var; bildirim baslikta zil olarak durur. */
  tabs: {
    home: 'Ana Sayfa',
    statement: 'Ekstre',
    pay: 'Odeme',
    catalog: 'Vitrin',
  },
  header: {
    notifications: 'Bildirimler',
    profile: 'Profil',
    campaigns: 'Kampanyalar',
    requests: 'Talep ve oneri',
    privacy: 'Gizlilik ve KVKK',
    close: 'Kapat',
  },
} as const;
