/** §12 — UI metinleri sozlukte tutulur; bilesenlere sabit metin gomulmez. */
export const tr = {
  app: {
    name: 'CariNet',
    tagline: 'B2B cari hesap platformu',
  },
  login: {
    title: 'Satici Paneli Girisi',
    email: 'E-posta',
    password: 'Sifre',
    totp: 'Dogrulama kodu (2FA)',
    submit: 'Giris yap',
    submitting: 'Giris yapiliyor...',
    forgot: 'Sifremi unuttum',
    genericError: 'Giris yapilamadi. Lutfen bilgilerinizi kontrol edin.',
  },
  nav: {
    dashboard: 'Ozet',
    buyers: 'Cari hesaplar',
    transactions: 'Hareketler',
    invoices: 'Faturalar',
    reports: 'Raporlar',
    collections: 'Tahsilat',
    imports: 'Ice aktarim',
    wizard: 'Gecis sihirbazi',
    representatives: 'Temsilciler',
    settings: 'Ayarlar',
    logout: 'Cikis yap',
  },
  collections: {
    title: 'Tahsilat',
    description:
      'Alici havale/EFT ile odedigi anda referans kodu eslesir; kartli odeme saticinin kendi POS"unda yapilir. Platform para akisina girmez.',
    pending: 'Bekleyen tahsilatlar',
    reference: 'Referans kodu',
    channel: 'Kanal',
    channels: {
      BANK_TRANSFER: 'Havale/EFT',
      CARD_POS: 'Kart (POS)',
    },
    statuses: {
      PENDING: 'Bekliyor',
      CONFIRMED: 'Onaylandi',
      EXPIRED: 'Suresi doldu',
      CANCELLED: 'Iptal',
    },
    expiresAt: 'Son gecerlilik',
    confirm: 'Onayla',
    confirmTitle: 'Tahsilati onayla',
    actualAmount: 'Gerceklesen tutar (farkliysa)',
    partialHint:
      'Gerceklesen tutar talep tutarindan azsa fark icin otomatik yeni bir talep acilir (§8).',
    note: 'Not',
    cancel: 'Iptal et',
    cancelReason: 'Iptal sebebi',
    newIntent: 'Yeni tahsilat talebi',
    amount: 'Tutar',
    statement: 'Banka ekstresi',
    statementHint:
      'Internet bankaciligindan indirdiginiz CSV/Excel ekstresini yukleyin. Sistem referans kodu ve cari koduna gore esler; onay SIZDE kalir.',
    uploadStatement: 'Ekstre yukle',
    skippedOutgoing: 'Atlanan cikis hareketi',
    match: 'Eslesme',
    confidence: {
      EXACT: 'Kesin',
      SUGGESTED: 'Oneri',
      NONE: 'Eslesmedi',
    },
    selectAccount: 'Cari sec',
    bulkConfirm: 'Secilenleri onayla',
    matched: 'Islenmis',
    confirmed: 'tahsilat onaylandi',
    remainderOpened: 'Kalan tutar icin yeni talep acildi.',
  },
  settings: {
    title: 'Ayarlar',
    description:
      'IBAN ve POS anahtari degisikligi KRITIK islemdir: iki adimli dogrulama istenir ve audit kaydi olusur (§11.3).',
    bankAccounts: 'Tahsilat IBAN"lari',
    bankName: 'Banka',
    iban: 'IBAN',
    holderName: 'Hesap sahibi',
    addBank: 'IBAN ekle',
    deactivate: 'Pasife al',
    pos: 'Sanal POS (kendi hesabiniz)',
    posHint:
      'Kart verisi sistemimize GIRMEZ: odeme saglayicinizin hosted 3D sayfasinda alinir, para dogrudan sizin hesabiniza gecer.',
    provider: 'Saglayici',
    merchantId: 'Uye isyeri no',
    apiKey: 'API anahtari',
    secret: 'Gizli anahtar',
    active: 'Aktif',
    totp: 'Dogrulama kodu (2FA)',
    totpHint: 'Iki adimli dogrulama kuruluysa kodunuzu girin.',
    save: 'Kaydet',
    posEmpty: 'Tanimli POS yok — kartli tahsilat kapali.',
  },
  guest: {
    title: 'Odeme yap',
    accountCode: 'Cari kodunuz',
    amount: 'Odeyeceginiz tutar',
    submit: 'Odeme talebi olustur',
    bankTransfer: 'Havale / EFT',
    card: 'Kredi karti',
    referenceTitle: 'Aciklamaya MUTLAKA bu kodu yazin',
    referenceHint:
      'Kod olmadan odemeniz otomatik eslesmez ve elle bulunmasi gerekir. Talebiniz 72 saat gecerlidir.',
    payAtProvider: 'Guvenli odeme sayfasina git',
    providerHint: 'Kart bilgileriniz bankanin sayfasinda alinir, bu sitede saklanmaz.',
    notFound: 'Satici bulunamadi.',
  },
  reports: {
    title: 'Raporlar',
    description:
      'Risk foyu: alacaklar en eski borctan baslayarak kapatilir (FIFO), kalan acik kalemler vadeye gore yaslandirilir.',
    balance: 'Bakiye',
    overdue: 'Vadesi gecen',
    notDue: 'Vadesi gelmemis',
    totalBalance: 'Toplam alacak',
    totalOverdue: 'Toplam vadesi gecen',
    overLimit: 'Limiti asan cari',
    limitUsage: 'Limit %',
    averageDue: 'Ortalama vade',
    periodic: 'Donemsel bakiye',
    openingBalance: 'Acilis bakiyesi',
    allAccounts: 'Tum cariler',
    aging: 'Yaslandirma',
    openItems: 'Acik kalemler',
    pdf: 'Ekstre PDF indir',
  },
  addresses: {
    title: 'Adresler',
    label: 'Etiket',
    fullAddress: 'Adres',
    city: 'Sehir',
    add: 'Adres ekle',
    delete: 'Sil',
  },
  dashboard: {
    title: 'Ozet',
    welcome: 'Hos geldiniz',
    activeContext: 'Aktif hesap',
    memberships: 'Uyelikleriniz',
    buyerAccounts: 'Cari hesaplar',
    totalReceivable: 'Toplam alacak',
    accountCount: 'Cari sayisi',
    overLimit: 'Limiti asan cari',
    empty: 'Kayit bulunamadi.',
  },
  buyers: {
    title: 'Cari hesaplar',
    description: 'Bakiye her istekte hareketlerden turetilir — saklanmaz.',
    new: 'Yeni cari',
    edit: 'Cariyi duzenle',
    search: 'Unvan, cari kodu veya VKN ara',
    balance: 'Bakiye',
    debit: 'Borc',
    credit: 'Alacak',
    limitUsage: 'Limit kullanimi',
    statement: 'Ekstre',
    invite: 'Davet linki uret',
    inviteReady: 'Davet linki hazir — alicinin telefonuna gonderin:',
    users: 'Kullanici',
    deactivate: 'Pasife al',
    activate: 'Aktife al',
    inactive: 'Pasif',
    codeHistory: 'Eski cari kodlari',
    vkn: 'VKN / TCKN',
    createdAt: 'Kayit tarihi',
  },
  transactions: {
    title: 'Hareketler',
    new: 'Yeni hareket',
    type: 'Tur',
    debit: 'Borc (DEBIT)',
    credit: 'Alacak (CREDIT)',
    documentType: 'Belge turu',
    documentNo: 'Belge no',
    documentDate: 'Belge tarihi',
    dueDate: 'Vade',
    amount: 'Tutar',
    currency: 'Para birimi',
    rate: 'Kur',
    description: 'Aciklama',
    runningBalance: 'Yuruyen bakiye',
    cancel: 'Iptal et',
    cancelReason: 'Iptal sebebi',
    cancelled: 'Iptal',
    cancelHint: 'Finansal kayit silinmez; iptal edilir ve audit kaydi olusur.',
  },
  invoices: {
    title: 'Faturalar',
    new: 'Yeni fatura',
    invoiceNo: 'Fatura no',
    invoiceDate: 'Fatura tarihi',
    items: 'Kalemler',
    addItem: 'Kalem ekle',
    itemName: 'Urun / hizmet',
    unit: 'Birim',
    quantity: 'Miktar',
    unitPrice: 'Birim fiyat',
    taxRate: 'KDV %',
    netTotal: 'Net toplam',
    taxTotal: 'KDV',
    grandTotal: 'Genel toplam',
    totalsHint: 'Toplamlar sunucuda decimal.js ile hesaplanir.',
    cancel: 'Faturayi iptal et',
  },
  imports: {
    title: 'Ice aktarim',
    description: 'Excel veya e-Fatura (UBL) dosyasi yukleyin. Onaylamadan hicbir kayit yazilmaz.',
    target: 'Hedef',
    targets: {
      BUYER_ACCOUNTS: 'Cari listesi',
      TRANSACTIONS: 'Hareketler',
      OPENING_BALANCES: 'Devir bakiyeleri',
      INVOICES: 'e-Fatura (UBL XML/ZIP)',
    },
    file: 'Dosya',
    upload: 'Yukle ve onizle',
    uploading: 'Yukleniyor...',
    preview: 'Onizleme',
    rowCount: 'Satir',
    validCount: 'Gecerli',
    errorCount: 'Hatali',
    duplicate: 'Bu dosya daha once yuklenmis (mukerrer uyarisi).',
    mapping: 'Kolon eslemesi',
    commit: 'Onayla ve isle',
    skipErrors: 'Hatali satirlari atla',
    cancelBatch: 'Yuklemeyi iptal et',
    committed: 'Islendi',
    errorsTitle: 'Hatali satirlar (satir no + sebep)',
    history: 'Yukleme gecmisi',
    result: 'Sonuc',
  },
  wizard: {
    title: 'Gecis sihirbazi',
    description:
      'Kesim tarihini secin, devir bakiyelerini yukleyin. Sistem tarihcenin tamamini degil, kesim gunundeki bakiyeyi tek DEVIR hareketi olarak alir (§9).',
    cutoff: 'Kesim tarihi',
    expectedTotal: 'Programinizdaki net toplam (dogrulama icin)',
    report: 'Dogrulama raporu',
    imported: 'Bizim hesabimiz',
    expected: 'Program toplami',
    difference: 'Fark',
    matches: 'Toplamlar tutuyor — go-live icin hazir.',
    mismatch: 'Fark kapanmadan devir islenemez.',
    newAccounts: 'Yeni acilacak cari',
    existingAccounts: 'Mevcut cari',
    commit: 'Deviri isle',
  },
  representatives: {
    title: 'Temsilciler',
    new: 'Yeni temsilci',
    fullName: 'Ad soyad',
    phone: 'Telefon',
    email: 'E-posta',
    accountCount: 'Cari sayisi',
    delete: 'Sil',
  },
  common: {
    loading: 'Yukleniyor...',
    error: 'Bir hata olustu.',
    save: 'Kaydet',
    saving: 'Kaydediliyor...',
    cancel: 'Vazgec',
    close: 'Kapat',
    back: 'Geri',
    accountCode: 'Cari kodu',
    buyer: 'Cari',
    title: 'Unvan',
    creditLimit: 'Kredi limiti',
    representative: 'Temsilci',
    none: 'Yok',
    empty: 'Kayit bulunamadi.',
    total: 'Toplam',
    page: 'Sayfa',
    prev: 'Onceki',
    next: 'Sonraki',
    copy: 'Kopyala',
    copied: 'Kopyalandi',
    actions: 'Islemler',
    date: 'Tarih',
    status: 'Durum',
    select: 'Seciniz',
  },
} as const;
